### ISSUE TITLE
Устройство репозитория

### ISSUE THREAD

**Issue by lounres** [orenty7/kotlin-task-1#1]
В идеале `gradlew`, `gradlew.bat`, `gradle/wrapper/gradle-wrapper.jar` и `gradle-wrapper.properties` нужно включать в VCS, ибо они необходимы для того, чтобы у всех членов команды разработки система сборки запускалась идентично. Для этого можно воспользоваться готовыми шаблонами `.gitignore`: либо в [репозитории `.gitignore`](https://github.com/github/gitignore), либо одноимённым плагином в IntelliJ IDEA.

**Comment by orenty7** [comment]
Добавил файлы в репозиторий
